### ISSUE TITLE
[DKG Engine and UIX - Data storage service ] Component Smoke tests 

### ISSUE THREAD

**Issue by RafyMehany** [glaciation-heu/IceStream#152]
## Task
Specify and run smoke tests for the Deployed service/component, the Goal is to run some tests against your service after its deployment on the Kubernetes cluster to make sure that it is working as expected,
you can achieve this task manually for now but later on, you will automate this.
This task involves setting up smoke tests for the service/component deployment, ensuring the reliability and stability of the deployed application.

## 1- Design Smoke Tests
**Smoke Test Specification**: Specify smoke tests to verify critical functionalities and basic usability of the deployed service/component.
*To accomplish this task effectively, it's essential to have access to the deployed service/component and sufficient knowledge of its functionalities and dependencies.*

## 2- Document this smoke tests
**Update Documents**: Update your documents to include your smoke tests so anybody can refer to them, and later on when you automate it, it will be documented so it will save time.

## 3- Run Smoke Tests
Run your tests after every deployment on the integration cluster to make sure that the service is working as expected.

**Example**: 
- Specify the critical and basic functionalities that the smoke tests will cover.
- Provide these smoke tests, like curl or API requests that you will fire to make sure that the service is working as expected after deployment
- Provide the expected results for each test.
- Provide the steps to run the smoke tests.
- Provide the steps to interpret the results.
- Update the documentation to include the smoke tests with the results.

## 4- Integration with Deployment Workflow (This step is optional for now)
**Integration with Deployment Workflow**: Integrate smoke testing into the deployment workflow to automate the process and ensure it runs seamlessly alongside other deployment steps.
you can achieve this using argoCD rollouts for more information check this [docs](https://argo-rollouts.readthedocs.io/en/stable/)
# Acceptance Criteria
- [ ] Proper access to the environment.
- [ ] Smoke tests are documented and cover critical functionalities.
- [ ] Smoke tests are run after every deployment on the integration cluster.
- [ ] Smoke testing is integrated into the deployment workflow (This is an option step for now)

## Note
- Ensure that smoke tests provide quick feedback on the health of the deployed service/component.
- Smoke tests should be designed to run efficiently without significantly impacting the deployment process.
- You will have to do the smoke testing every time after a new deployment on the integration cluster.
# Additional Information
- [Smoke Testing](https://www.linkedin.com/pulse/smoke-testing-explanation-examples-maria-martin/)
