### ISSUE TITLE
[Live analytics, edge computation]  Component Stubs Implementation, Service Dockerization and Helm chart for SAP 

### ISSUE THREAD

**Issue by RafyMehany** [glaciation-heu/IceStream#73]
# Task: 
Include Service Stubs Implementation, service Dockerization, and Helm Chart.

## 1- Service Stubs Overview:
- **Description**: Introduce the implementation of service stubs, emphasizing that they serve as preliminary placeholders for the forthcoming actual implementation.
- **API Documentation**: Detail the evolving API endpoints, methods, and the anticipated responses as part of the ongoing implementation.
- **Upcoming Features**: Provide insight into planned enhancements and features to be implemented.

## 2- Standalone Run:
- **Instructions**: Clearly outline the steps to run the evolving service stubs (service/component) in a standalone mode during the implementation phase.
- **Configuration Updates**: Highlight any configuration adjustments or new environment variables introduced during the ongoing implementation.

## 4- Dockerization service/component:
- **Dockerfile creating**: Create a Dockerfile to support the evolving service stubs and make your service up and running.
- **Build and Run**: Include updated instructions for building the Docker image and running the service/component in a Docker container.

## 5- Helm Chart Deployment:
- **Helm Chart Development**: create Helm chart for the service/component.
- **Values Configuration**: Describe any considerations for customizing configurations using Helm values in anticipation of deployment.

# Acceptance Criteria:
- [x] Service stubs
- [x] Service/component standalone run with steps
- [x] Service/component Dockerization 
- [x] Service/component  Helm Chart

# Additional Information:
- Diagrams - [draw.io](http://draw.io/) or [mermaid.live](http://mermaid.live/) committed to the GitHub repository.
- All documents and diagrams should be placed in markdown `.md` files in the service directory `<service>/docs`.
- Refer to examples in the [sample report](https://github.com/glaciation-heu/foobar_sandbox/blob/main/docs) and [Documentation](https://github.com/glaciation-heu/foobar_sandbox/blob/main/editing_guide.md) for creating diagrams, editing files, templates, etc.
- You can delete this placeholder text if you got it.
